apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: image-worker-scaler
  namespace: kcc
  labels:
    app: image-worker
spec:
  scaleTargetRef:
    name: image-worker
  minReplicaCount: 1
  maxReplicaCount: 10
  pollingInterval: 15
  cooldownPeriod: 60
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: kcc-event-hubs.servicebus.windows.net:9093
        consumerGroup: agent-workers
        topic: farmer-messages-image
        lagThreshold: "5"
        offsetResetPolicy: earliest
      authenticationRef:
        name: kcc-kafka-auth
